import { initializeApp } from "https://www.gstatic.com/firebasejs/12.11.0/firebase-app.js";
import { getAuth, onAuthStateChanged, updatePassword } from "https://www.gstatic.com/firebasejs/12.11.0/firebase-auth.js";
import { getFirestore, collection, addDoc, getDocs, query, orderBy, deleteDoc, doc, getDoc, updateDoc } from "https://www.gstatic.com/firebasejs/12.11.0/firebase-firestore.js";
import { getStorage, ref, uploadBytes, getDownloadURL } from "https://www.gstatic.com/firebasejs/12.11.0/firebase-storage.js";

const firebaseConfig = {
    apiKey: "Give Your own API",
    authDomain: "expensetracker-85a50.firebaseapp.com",
    projectId: "expensetracker-85a50",
    storageBucket: "expensetracker-85a50.firebasestorage.app",
    messagingSenderId: "622489677206",
    appId: "1:622489677206:web:6c8c52deff322a253c81b7",
    measurementId: "G-0R6M9MXL9E"
};

const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);
const storage = getStorage(app); 

let transactions = [];
let currentUserUid = null;
let userCurrency = '₹'; 
let currentUserPhotoURL = ""; 
let currentSort = { column: null, direction: 'asc' };
let currentFilter = { type: 'all', value: '' };

let monthlyBudgetLimit = localStorage.getItem('monthlyBudget') ? parseFloat(localStorage.getItem('monthlyBudget')) : 15000;
let availableYears = []; 

let userCategories = {
    income: ['Business', 'Freelance', 'Investment', 'Salary', 'Other'],
    expense: ['Entertainment', 'Food & Health', 'Investment', 'Shopping', 'Transport', 'Utilities', 'Other']
};
let activeCategoryTab = 'expense';

const dateObj = new Date();
const today = `${dateObj.getFullYear()}-${String(dateObj.getMonth() + 1).padStart(2, '0')}-${String(dateObj.getDate()).padStart(2, '0')}`;
const currentMonthStr = today.substring(0, 7);

let donutChartType = 'expense'; 
let expenseChartCurrentFilter = { type: 'month', value: currentMonthStr };

// --- HELPER FUNCTION: Sort Categories with "Other" Always Last ---
function sortCategoriesWithOtherLast(categoriesArray) {
    return categoriesArray.slice().sort((a, b) => {
        if (a === 'Other') return 1;
        if (b === 'Other') return -1;
        return a.localeCompare(b);
    });
}

document.addEventListener("DOMContentLoaded", () => {
    document.getElementById("incomeDate").value = today;
    document.getElementById("expenseDate").value = today;
});

onAuthStateChanged(auth, async (user) => {
    if (user) {
        currentUserUid = user.uid;
        try {
            const userDoc = await getDoc(doc(db, "users", currentUserUid));
            if (userDoc.exists()) {
                const data = userDoc.data();
                if (data.currency) userCurrency = data.currency;
                if (data.categories) userCategories = data.categories;
            }
        } catch(e) { console.error("Error loading user data", e); }

        window.renderCategoryDropdowns();
        await fetchTransactionsFromCloud();
        
        await window.processRecurringBills();
        
        updateDashboard(); 
        window.initOverviewFilters(); 
        updateTransactionsTable();
    }
});

window.processRecurringBills = async function() {
    if (!currentUserUid) return;

    const now = new Date();
    const todayTime = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime();

    const parents = transactions.filter(t => t.recurring && t.recurring !== 'none' && !t.isAutoGenerated);
    let generatedCount = 0;

    for (const parent of parents) {
        const pParts = parent.date.split('-');
        let currDate = new Date(pParts[0], pParts[1] - 1, pParts[2]);
        let expectedDates = [];

        while (true) {
            if (parent.recurring === 'daily') {
                currDate.setDate(currDate.getDate() + 1);
            } else if (parent.recurring === 'weekly') {
                currDate.setDate(currDate.getDate() + 7);
            } else if (parent.recurring === 'monthly') {
                currDate.setMonth(currDate.getMonth() + 1);
            } else if (parent.recurring === 'yearly') {
                currDate.setFullYear(currDate.getFullYear() + 1);
            }

            if (currDate.getTime() > todayTime) break;

            const expectedDateStr = `${currDate.getFullYear()}-${String(currDate.getMonth() + 1).padStart(2, '0')}-${String(currDate.getDate()).padStart(2, '0')}`;
            expectedDates.push(expectedDateStr);
        }

        for (const expectedDate of expectedDates) {
            const exists = transactions.some(t => 
                (t.parentId === parent.id || t.description === `[Auto-Recurring] ${parent.description || ''}`) && 
                t.date === expectedDate
            );

            if (!exists) {
                const autoTx = {
                    id: Date.now() + Math.floor(Math.random() * 1000), 
                    date: expectedDate,
                    category: parent.category,
                    amount: parent.amount,
                    status: "Success",
                    type: parent.type || (parent.amount > 0 ? "income" : "expense"),
                    description: `[Auto-Recurring] ${parent.description || ''}`,
                    recurring: 'none', 
                    isAutoGenerated: true,
                    parentId: parent.id 
                };

                try {
                    const docRef = await addDoc(collection(db, "users", currentUserUid, "transactions"), autoTx);
                    autoTx.docId = docRef.id;
                    transactions.unshift(autoTx);
                    generatedCount++;
                } catch(e) { console.error("Error auto-billing", e); }
            }
        }
    }
    
    if (generatedCount > 0) {
        showNotification(`${generatedCount} recurring transactions auto-generated up to today.`, "info");
    }
};

window.toggleRecurring = async function(docId, txId) {
    const tx = transactions.find(t => t.id === txId);
    if (!tx) return;

    if (tx.isAutoGenerated) {
        showNotification("Cannot set recurrence on an auto-generated entry. Edit the original transaction.", "error");
        return;
    }
    
    if (tx.recurring && tx.recurring !== 'none') {
        document.getElementById('stopRecurringDocId').value = docId;
        document.getElementById('stopRecurringTxId').value = txId;
        document.getElementById('stopRecurringModal').style.display = 'block';
        document.body.style.overflow = 'hidden';
    } else {
        document.getElementById('recurringDocId').value = docId;
        document.getElementById('recurringTxId').value = txId;
        document.getElementById('recurringModal').style.display = 'block';
        document.body.style.overflow = 'hidden';
    }
};

window.saveRecurringFrequency = async function() {
    const docId = document.getElementById('recurringDocId').value;
    const txId = parseInt(document.getElementById('recurringTxId').value);
    const frequency = document.getElementById('recurringFrequencySelect').value;
    
    const tx = transactions.find(t => t.id === txId);
    if (!tx) return;
    
    tx.recurring = frequency;
    
    if (currentUserUid && docId) {
        try { await updateDoc(doc(db, "users", currentUserUid, "transactions", docId), { recurring: frequency }); } 
        catch (e) { console.error("Error saving frequency", e); }
    }
    
    window.closeModal('recurringModal');
    showNotification(`Set to recur ${frequency}`, "success");
    
    await window.processRecurringBills();
    
    updateDashboard();
    updateTransactionsTable();
};

window.confirmStopRecurring = async function(action) {
    const docId = document.getElementById('stopRecurringDocId').value;
    const txId = parseInt(document.getElementById('stopRecurringTxId').value);
    
    const tx = transactions.find(t => t.id === txId);
    if (!tx) return;

    tx.recurring = 'none';
    if (currentUserUid && docId) {
        try { await updateDoc(doc(db, "users", currentUserUid, "transactions", docId), { recurring: 'none' }); }
        catch(e) { console.error(e); }
    }

    if (action === 'delete') {
        const children = transactions.filter(t => 
            t.parentId === txId || 
            (t.isAutoGenerated && t.description === `[Auto-Recurring] ${tx.description || ''}` && t.category === tx.category)
        );

        for (const child of children) {
            transactions = transactions.filter(t => t.id !== child.id);
            if (currentUserUid && child.docId) {
                try { await deleteDoc(doc(db, "users", currentUserUid, "transactions", child.docId)); }
                catch(e) { console.error(e); }
            }
        }
        showNotification("Recurrence stopped & generated history deleted.", "success");
    } else {
        showNotification("Recurrence stopped (Past history kept).", "success");
    }

    window.closeModal('stopRecurringModal');
    updateDashboard();
    updateTransactionsTable();
};

// ==========================================================================
// TABLE CATEGORY MULTI-SELECT FILTER
// ==========================================================================
window.selectedTableCategories = [];

window.renderTableCategoryFilter = function() {
    const container = document.getElementById('tableCategoryFilterDropdown');
    if (!container) return;

    // Use custom sort to keep "Other" at the bottom
    const allCats = sortCategoriesWithOtherLast([...new Set([...userCategories.income, ...userCategories.expense])]);

    let html = '<div style="margin-bottom: 0.5rem; font-size: 0.8rem; font-weight: 600; color: var(--text-muted);">Filter Categories</div>';
    
    allCats.forEach(cat => {
        const isChecked = window.selectedTableCategories.includes(cat) ? 'checked' : '';
        html += `
            <div style="display: flex; align-items: center; gap: 0.5rem; margin-bottom: 0.4rem;">
                <input type="checkbox" id="catFilter_${cat}" value="${cat}" class="table-cat-checkbox" ${isChecked}>
                <label for="catFilter_${cat}" style="font-size: 0.85rem; cursor: pointer; color: var(--text-main);">${cat}</label>
            </div>
        `;
    });

    html += `
        <div style="display: flex; justify-content: space-between; gap: 0.5rem; margin-top: 0.75rem;">
            <button class="btn btn-secondary" style="padding: 0.4rem; font-size: 0.75rem; flex: 1;" onclick="window.clearTableCategoryFilter(event)">Clear</button>
            <button class="btn btn-primary" style="padding: 0.4rem; font-size: 0.75rem; flex: 1;" onclick="window.applyTableCategoryFilter(event)">Apply</button>
        </div>
    `;
    container.innerHTML = html;
};

window.toggleTableCategoryFilter = function(e) {
    e.stopPropagation();
    window.renderTableCategoryFilter();
    document.getElementById('tableCategoryFilterDropdown').classList.toggle('show');
};

window.applyTableCategoryFilter = function(e) {
    e.stopPropagation();
    const checkboxes = document.querySelectorAll('.table-cat-checkbox:checked');
    window.selectedTableCategories = Array.from(checkboxes).map(cb => cb.value);
    document.getElementById('tableCategoryFilterDropdown').classList.remove('show');
    
    const icon = document.getElementById('filter-icon-category');
    if (window.selectedTableCategories.length > 0) icon.style.color = '#3b82f6';
    else icon.style.color = '#9ca3af';
    
    updateTransactionsTable();
};

window.clearTableCategoryFilter = function(e) {
    e.stopPropagation();
    window.selectedTableCategories = [];
    document.getElementById('tableCategoryFilterDropdown').classList.remove('show');
    document.getElementById('filter-icon-category').style.color = '#9ca3af';
    updateTransactionsTable();
};

// ==========================================================================
// FEATURE: CUSTOM CATEGORY MANAGEMENT
// ==========================================================================
window.renderCategoryDropdowns = function() {
    const incSelect = document.getElementById('incomeCategory');
    const expSelect = document.getElementById('expenseCategory');
    
    if (incSelect) {
        incSelect.innerHTML = '<option value="">Select category</option>';
        sortCategoriesWithOtherLast(userCategories.income).forEach(cat => { 
            incSelect.innerHTML += `<option value="${cat}">${cat}</option>`; 
        });
    }
    if (expSelect) {
        expSelect.innerHTML = '<option value="">Select category</option>';
        sortCategoriesWithOtherLast(userCategories.expense).forEach(cat => { 
            expSelect.innerHTML += `<option value="${cat}">${cat}</option>`; 
        });
    }
};

window.openCategoryModal = function() {
    document.getElementById('profileDropdown').classList.remove('show');
    document.getElementById('categoryModal').style.display = 'block';
    document.body.style.overflow = 'hidden';
    window.switchCategoryManagerTab('expense'); 
};

window.switchCategoryManagerTab = function(type) {
    activeCategoryTab = type;
    document.getElementById('catTabExpense').classList.toggle('active', type === 'expense');
    document.getElementById('catTabIncome').classList.toggle('active', type === 'income');
    window.renderCategoryManagerList();
};

window.renderCategoryManagerList = function() {
    const listEl = document.getElementById('categoryManagerList');
    listEl.innerHTML = '';
    
    const categoriesToShow = sortCategoriesWithOtherLast(userCategories[activeCategoryTab]);
    
    categoriesToShow.forEach(cat => {
        const deleteBtn = cat !== 'Other' 
            ? `<button class="category-delete-btn" onclick="window.deleteCategory('${cat}')" title="Delete Category"><i class="fas fa-trash-alt"></i></button>` 
            : `<span><i class="fas fa-lock" style="color: #9ca3af; font-size: 0.8rem;" title="Default category cannot be deleted"></i></span>`;
        listEl.innerHTML += `<li class="category-list-item"><span>${cat}</span>${deleteBtn}</li>`;
    });
};

window.addNewCategory = async function() {
    const inputEl = document.getElementById('newCategoryInput');
    let newCat = inputEl.value.trim();
    if (!newCat) return;
    newCat = newCat.charAt(0).toUpperCase() + newCat.slice(1); 
    
    if (userCategories[activeCategoryTab].includes(newCat)) { showNotification("Category already exists!", "error"); return; }
    
    userCategories[activeCategoryTab].push(newCat);
    inputEl.value = '';
    
    await window.saveCategoriesToCloud();
    window.renderCategoryManagerList(); window.renderCategoryDropdowns();
    showNotification(`Added ${newCat} to ${activeCategoryTab}s`, "success");
};

window.deleteCategory = async function(catToDelete) {
    if (!confirm(`Delete category "${catToDelete}"? (Past transactions will keep this name)`)) return;
    userCategories[activeCategoryTab] = userCategories[activeCategoryTab].filter(c => c !== catToDelete);
    await window.saveCategoriesToCloud();
    window.renderCategoryManagerList(); window.renderCategoryDropdowns();
    showNotification(`Deleted category ${catToDelete}`, "info");
};

window.saveCategoriesToCloud = async function() {
    if (!currentUserUid) return;
    try { await updateDoc(doc(db, "users", currentUserUid), { categories: userCategories }); } 
    catch (e) { showNotification("Failed to save categories to cloud", "error"); }
};

// ==========================================================================
// CSV EXPORT
// ==========================================================================
window.exportData = function() { 
    if (transactions.length === 0) { showNotification("No transactions to export!", "error"); return; }

    const headers = ["Date", "Category", "Description", "Type", "Amount", "Status", "Is Recurring"];
    const rows = transactions.map(t => [
        t.date, t.category, `"${t.description || ''}"`, t.type || (t.amount > 0 ? "income" : "expense"),
        Math.abs(t.amount), t.status, (t.recurring && t.recurring !== 'none') ? t.recurring : "No"
    ]);

    const csvContent = [headers, ...rows].map(e => e.join(",")).join("\n");
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement("a");
    link.setAttribute("href", URL.createObjectURL(blob));
    link.setAttribute("download", `My_Expenses_${new Date().toLocaleDateString()}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    showNotification("CSV Exported successfully!", "success");
}

async function fetchTransactionsFromCloud() {
    if (!currentUserUid) return;
    try {
        const q = query(collection(db, "users", currentUserUid, "transactions"), orderBy("id", "desc"));
        const querySnapshot = await getDocs(q);
        transactions = [];
        querySnapshot.forEach((doc) => {
            let data = doc.data();
            data.docId = doc.id; 
            transactions.push(data);
        });
    } catch (error) { console.error(error); }
}

window.previewEditPhoto = function(event) {
    const file = event.target.files[0];
    if (file) {
        const reader = new FileReader();
        reader.onload = function(e) { document.getElementById('editProfilePreview').src = e.target.result; };
        reader.readAsDataURL(file);
    }
};

window.viewProfile = async function() {
    if (!currentUserUid) return;
    try {
        const userDoc = await getDoc(doc(db, "users", currentUserUid));
        if (userDoc.exists()) {
            const data = userDoc.data();
            const fullName = data.fullName || 'User';
            currentUserPhotoURL = data.photoURL || ""; 
            
            document.getElementById('editName').value = fullName;
            document.getElementById('editCurrency').value = data.currency || '₹';
            
            const fallbackAvatar = `https://ui-avatars.com/api/?name=${encodeURIComponent(fullName)}&background=3b82f6&color=fff&size=128&bold=true`;
            document.getElementById('editProfilePreview').src = currentUserPhotoURL ? currentUserPhotoURL : fallbackAvatar;
        }
        document.getElementById('editPassword').value = ''; 
        document.getElementById('profileDropdown').classList.remove('show');
        document.getElementById('profileModal').style.display = 'block';
        document.body.style.overflow = 'hidden';
    } catch (error) { showNotification("Error loading profile", "error"); }
};

window.saveProfile = async function() {
    const btn = document.getElementById('saveProfileBtn');
    btn.textContent = "Saving...";
    btn.disabled = true;

    const newName = document.getElementById('editName').value;
    const newCurrency = document.getElementById('editCurrency').value;
    const newPassword = document.getElementById('editPassword').value;
    const photoInput = document.getElementById('editPhotoInput');
    
    try {
        let finalPhotoURL = currentUserPhotoURL; 

        if (photoInput.files && photoInput.files[0]) {
            const file = photoInput.files[0];
            const storageRef = ref(storage, `profile_photos/${currentUserUid}`);
            await uploadBytes(storageRef, file);
            finalPhotoURL = await getDownloadURL(storageRef);
            currentUserPhotoURL = finalPhotoURL; 
        }

        await updateDoc(doc(db, "users", currentUserUid), { fullName: newName, currency: newCurrency, photoURL: finalPhotoURL });
        if (newPassword.trim() !== '') await updatePassword(auth.currentUser, newPassword);

        userCurrency = newCurrency; 
        const fallbackAvatar = `https://ui-avatars.com/api/?name=${encodeURIComponent(newName)}&background=3b82f6&color=fff&size=128&bold=true`;
        document.getElementById('profileAvatar').src = finalPhotoURL ? finalPhotoURL : fallbackAvatar;
        
        const hour = new Date().getHours();
        let timeGreeting = "Good Morning";
        if (hour >= 12 && hour < 17) timeGreeting = "Good Afternoon";
        else if (hour >= 17) timeGreeting = "Good Evening";
        document.getElementById('greetingText').textContent = `${timeGreeting}, ${newName.split(' ')[0]}!`;

        updateDashboard(); window.initOverviewFilters(); updateTransactionsTable(); window.closeModal('profileModal');
        showNotification("Profile updated successfully!", "success");

    } catch (error) {
        if (error.code === 'auth/requires-recent-login') alert("For security reasons, Firebase requires you to Sign Out and Sign Back In before changing your password.");
        else if (error.code === 'auth/weak-password') showNotification("Password must be at least 6 characters.", "error");
        else showNotification("Error saving profile.", "error");
    } finally {
        btn.textContent = "Save Changes"; btn.disabled = false;
    }
};

window.openIncomeModal = function() { document.getElementById("incomeModal").style.display = "block"; document.body.style.overflow = "hidden"; };
window.openExpenseModal = function() { document.getElementById("expenseModal").style.display = "block"; document.body.style.overflow = "hidden"; };
window.openBudgetModal = function() { document.getElementById("budgetInput").value = monthlyBudgetLimit; document.getElementById("budgetModal").style.display = "block"; document.body.style.overflow = "hidden"; };

window.closeModal = function(modalId) {
    document.getElementById(modalId).style.display = "none";
    document.body.style.overflow = "auto";
    if (modalId === "incomeModal") { 
        document.getElementById("incomeForm").reset(); 
        document.getElementById("incomeDate").value = today; 
        document.getElementById("incomeRecurring").value = 'none'; 
    } else if (modalId === "expenseModal") { 
        document.getElementById("expenseForm").reset(); 
        document.getElementById("expenseDate").value = today; 
        document.getElementById("expenseRecurring").value = 'none'; 
    }
};

window.addIncome = async function() {
    const amount = parseFloat(document.getElementById("incomeAmount").value);
    const category = document.getElementById("incomeCategory").value;
    const description = document.getElementById("incomeDescription").value;
    const date = document.getElementById("incomeDate").value;
    const recurringEl = document.getElementById("incomeRecurring");
    const isRecurring = recurringEl ? recurringEl.value : 'none';
    
    if (!amount || !category || !date) { alert("Please fill in all required fields"); return; }
    
    const newTx = { 
        id: Date.now(), date: date, category: category, amount: amount, status: "Success", 
        type: "income", description: description, recurring: isRecurring 
    };
    
    transactions.unshift(newTx);
    
    if (currentUserUid) {
        try { 
            const docRef = await addDoc(collection(db, "users", currentUserUid, "transactions"), newTx); 
            newTx.docId = docRef.id; 
        } catch (e) { console.error("Error saving income: ", e); }
    }

    await window.processRecurringBills(); 
    updateDashboard(); updateTransactionsTable(); window.initOverviewFilters(); window.closeModal("incomeModal"); 
    showNotification("Income added successfully!", "success");
};

window.addExpense = async function() {
    const amount = parseFloat(document.getElementById("expenseAmount").value);
    const category = document.getElementById("expenseCategory").value;
    const description = document.getElementById("expenseDescription").value;
    const date = document.getElementById("expenseDate").value;
    const recurringEl = document.getElementById("expenseRecurring");
    const isRecurring = recurringEl ? recurringEl.value : 'none';
    
    if (!amount || !category || !date) { alert("Please fill in all required fields"); return; }
    
    const newTx = { 
        id: Date.now(), date: date, category: category, amount: -amount, status: "Success", 
        type: "expense", description: description, recurring: isRecurring
    };
    
    transactions.unshift(newTx);
    
    if (currentUserUid) {
        try { 
            const docRef = await addDoc(collection(db, "users", currentUserUid, "transactions"), newTx); 
            newTx.docId = docRef.id; 
        } catch (e) { console.error("Error saving expense: ", e); }
    }

    await window.processRecurringBills();
    updateDashboard(); updateTransactionsTable(); window.initOverviewFilters(); window.closeModal("expenseModal"); 
    showNotification("Expense added successfully!", "success");
};

window.deleteTransaction = async function(docId, txId) {
    if (!confirm("Are you sure you want to delete this transaction?")) return;
    
    transactions = transactions.filter(t => t.id !== txId);
    updateDashboard(); updateTransactionsTable(); window.initOverviewFilters();
    showNotification("Transaction deleted", "info");
    
    if (currentUserUid && docId) {
        try { await deleteDoc(doc(db, "users", currentUserUid, "transactions", docId)); } 
        catch(e) { console.error("Error deleting document: ", e); }
    }
};

window.saveBudget = function() {
    const newBudget = parseFloat(document.getElementById("budgetInput").value);
    if (!newBudget || newBudget <= 0) { alert("Please enter a valid budget amount"); return; }
    
    monthlyBudgetLimit = newBudget; 
    localStorage.setItem('monthlyBudget', monthlyBudgetLimit);
    updateDashboard(); window.closeModal("budgetModal"); 
    showNotification("Budget updated successfully!", "info");
};

// ==========================================================================
// DASHBOARD LOGIC
// ==========================================================================
function updateDashboard() {
    const now = new Date();
    const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1).getTime();
    const startOfLastMonth = new Date(now.getFullYear(), now.getMonth() - 1, 1).getTime();
    let thisMonthInc = 0, lastMonthInc = 0, thisMonthExp = 0, lastMonthExp = 0;

    transactions.forEach(t => {
        const parts = t.date.split('-');
        const tTime = new Date(parts[0], parts[1] - 1, parts[2]).getTime();
        const amt = Math.abs(t.amount);
        
        if (tTime >= startOfMonth) { 
            if (t.amount > 0) thisMonthInc += amt; 
            else thisMonthExp += amt; 
        } else if (tTime >= startOfLastMonth && tTime < startOfMonth) { 
            if (t.amount > 0) lastMonthInc += amt; 
            else lastMonthExp += amt; 
        }
    });

    document.getElementById("incomeAmountDisplay").textContent = `${userCurrency}${thisMonthInc.toLocaleString()}.00`;
    document.getElementById("expenseAmountDisplay").textContent = `${userCurrency}${thisMonthExp.toLocaleString()}.00`;

    let incChange = 0;
    if (lastMonthInc === 0) incChange = thisMonthInc > 0 ? 100 : 0;
    else incChange = ((thisMonthInc - lastMonthInc) / lastMonthInc) * 100;

    let expChange = 0;
    if (lastMonthExp === 0) expChange = thisMonthExp > 0 ? 100 : 0;
    else expChange = ((thisMonthExp - lastMonthExp) / lastMonthExp) * 100;

    const incChangeEl = document.getElementById('incomeChange');
    if (thisMonthInc === 0 && lastMonthInc === 0) { incChangeEl.innerHTML = `<i class="fas fa-minus"></i> 0% vs Last month`; incChangeEl.className = 'change'; } 
    else if (incChange >= 0) { incChangeEl.innerHTML = `<i class="fas fa-arrow-up"></i> ${incChange.toFixed(1)}% vs Last month`; incChangeEl.className = 'change'; } 
    else { incChangeEl.innerHTML = `<i class="fas fa-arrow-down"></i> ${Math.abs(incChange).toFixed(1)}% vs Last month`; incChangeEl.className = 'change2'; }

    const expChangeEl = document.getElementById('expenseChange');
    if (thisMonthExp === 0 && lastMonthExp === 0) { expChangeEl.innerHTML = `<i class="fas fa-minus"></i> 0% vs Last month`; expChangeEl.className = 'change'; } 
    else if (expChange >= 0) { expChangeEl.innerHTML = `<i class="fas fa-arrow-up"></i> ${expChange.toFixed(1)}% vs Last month`; expChangeEl.className = 'change2'; } 
    else { expChangeEl.innerHTML = `<i class="fas fa-arrow-down"></i> ${Math.abs(expChange).toFixed(1)}% vs Last month`; expChangeEl.className = 'change'; }

    let percentage = 0;
    if (monthlyBudgetLimit > 0) percentage = (thisMonthExp / monthlyBudgetLimit) * 100;
    
    if (percentage >= 100) showNotification("ALERT: Budget Exceeded!", "error");
    else if (percentage >= 80) showNotification("Warning: You have used 80% of your budget.", "info");
    
    document.getElementById("budgetLimitDisplay").textContent = `of ${userCurrency}${monthlyBudgetLimit.toLocaleString()}.00 limit`;
    document.getElementById("budgetUsedDisplay").textContent = `${userCurrency}${thisMonthExp.toLocaleString()}.00`;
    
    const progressFill = document.getElementById("budgetProgressFill");
    progressFill.style.width = `${Math.min(percentage, 100)}%`;
    if (percentage >= 100) progressFill.style.background = "#ef4444"; 
    else if (percentage >= 80) progressFill.style.background = "#f97316"; 
    else progressFill.style.background = "#fbbf24"; 

    let allTimeInc = 0, allTimeExp = 0, thisYearInc = 0, thisYearExp = 0;
    const currentYearStr = now.getFullYear().toString();

    transactions.forEach(t => {
        const amt = Math.abs(t.amount);
        const isInc = t.amount > 0;
        if (isInc) allTimeInc += amt; else allTimeExp += amt;
        if (t.date.substring(0,4) === currentYearStr) {
            if (isInc) thisYearInc += amt; else thisYearExp += amt;
        }
    });

    const formatSavings = (val, elId) => {
        const el = document.getElementById(elId);
        if (el) {
            el.textContent = `${val >= 0 ? '+' : '-'}${userCurrency}${Math.abs(val).toLocaleString()}`;
            el.style.color = val >= 0 ? '#34d399' : '#f87171'; 
        }
    };

    formatSavings(lastMonthInc - lastMonthExp, 'savedLastMonth');
    formatSavings(thisYearInc - thisYearExp, 'savedThisYear');
    formatSavings(allTimeInc - allTimeExp, 'savedAllTime');
    
    window.initSavingsCompare();
    updateBreakdowns();
    updateExpenseChart();
}

function updateBreakdowns() {
    const expenseTransactions = transactions.filter(t => t.amount < 0);
    const incomeTransactions = transactions.filter(t => t.amount > 0);
    
    const now = new Date();
    const startOfDay = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime();
    const dayOfWeek = now.getDay();
    const daysToMonday = dayOfWeek === 0 ? 6 : dayOfWeek - 1; 
    const startOfWeek = startOfDay - (daysToMonday * 24 * 60 * 60 * 1000); 
    const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1).getTime();

    function processBreakdown(txs, dailyId, weeklyId, monthlyId, listId, colorBarId) {
        let daily = 0, weekly = 0, monthly = 0, total = 0;
        const categoryTotals = {};

        txs.forEach(t => {
            const parts = t.date.split('-');
            const tTime = new Date(parts[0], parts[1] - 1, parts[2]).getTime();
            const absAmount = Math.abs(t.amount);
            
            if (tTime >= startOfMonth) {
                monthly += absAmount; 
                total += absAmount;
                if (!categoryTotals[t.category]) categoryTotals[t.category] = 0;
                categoryTotals[t.category] += absAmount;
                if (tTime >= startOfDay) daily += absAmount;
                if (tTime >= startOfWeek) weekly += absAmount;
            }
        });

        document.getElementById(dailyId).textContent = `${userCurrency}${daily.toLocaleString()}.00`;
        document.getElementById(weeklyId).textContent = `${userCurrency}${weekly.toLocaleString()}.00`;
        document.getElementById(monthlyId).textContent = `${userCurrency}${monthly.toLocaleString()}.00`;

        // Sort by amount, but force 'Other' to be at the bottom
        const sortedCategories = Object.keys(categoryTotals).map(cat => { return { name: cat, amount: categoryTotals[cat] }; }).sort((a, b) => {
            if (a.name === 'Other') return 1;
            if (b.name === 'Other') return -1;
            return b.amount - a.amount;
        });

        const categoriesList = document.getElementById(listId);
        categoriesList.innerHTML = '';
        
        const colors = ['#ea580c', '#f59e0b', '#eab308', '#10b981', '#3b82f6', '#8b5cf6', '#ec4899'];
        let colorBarGradient = [], currentPercentage = 0;

        sortedCategories.forEach((cat, index) => {
            const color = colors[index % colors.length];
            let percentage = 0;
            if (total > 0) percentage = (cat.amount / total) * 100;
            if (percentage > 0) { colorBarGradient.push(`${color} ${currentPercentage}% ${currentPercentage + percentage}%`); currentPercentage += percentage; }

            categoriesList.innerHTML += `
                <li class="expense-category">
                    <div class="category-info"><div class="category-dot" style="background-color: ${color}"></div><span>${cat.name}</span></div>
                    <div style="text-align: right;"><div style="font-weight: 600;">${userCurrency}${cat.amount.toLocaleString()}.00</div><div style="font-size: 0.7rem; color: #6b7280;">${percentage.toFixed(1)}%</div></div>
                </li>
            `;
        });
        const colorBar = document.getElementById(colorBarId);
        if (colorBarGradient.length > 0) colorBar.style.background = `linear-gradient(to right, ${colorBarGradient.join(', ')})`;
        else colorBar.style.background = '#e5e7eb'; 
    }

    processBreakdown(expenseTransactions, 'dailyExpense', 'weeklyExpense', 'monthlyExpense', 'expenseCategoriesList', 'expenseColorBar');
    processBreakdown(incomeTransactions, 'dailyIncome', 'weeklyIncome', 'monthlyIncome', 'incomeCategoriesList', 'incomeColorBar');
}

function updateExpenseChart() {
    let filteredData = transactions;
    if (donutChartType === 'expense') filteredData = filteredData.filter(t => t.amount < 0);
    else filteredData = filteredData.filter(t => t.amount > 0);

    if (expenseChartCurrentFilter.type !== 'all' && expenseChartCurrentFilter.value) {
        filteredData = filteredData.filter(t => t.date.startsWith(expenseChartCurrentFilter.value));
    }

    let total = 0;
    const categoryTotals = {};
    filteredData.forEach(t => {
        const amt = Math.abs(t.amount); 
        total += amt;
        if (!categoryTotals[t.category]) categoryTotals[t.category] = 0;
        categoryTotals[t.category] += amt;
    });

    document.getElementById('donutTotalAmount').textContent = `${userCurrency}${total.toLocaleString()}.00`;
    
    // Sort by amount, but force 'Other' to be at the bottom
    const sortedCategories = Object.keys(categoryTotals).map(cat => { return { name: cat, amount: categoryTotals[cat] }; }).sort((a, b) => {
        if (a.name === 'Other') return 1;
        if (b.name === 'Other') return -1;
        return b.amount - a.amount;
    });
    
    let colors = donutChartType === 'expense' ? ['#ea580c', '#f59e0b', '#eab308', '#10b981', '#3b82f6', '#8b5cf6', '#ec4899'] : ['#10b981', '#3b82f6', '#8b5cf6', '#ec4899', '#ea580c', '#f59e0b', '#eab308'];
    let conicString = ''; let currentDeg = 0;
    const legendsList = document.getElementById('expenseChartLegends'); 
    legendsList.innerHTML = '';

    if (total === 0) {
        document.getElementById('expenseDoughnutChart').style.background = `conic-gradient(#e5e7eb 0% 100%)`;
        legendsList.innerHTML = `<div style="text-align:center; color:#6b7280; padding: 1rem; font-size:0.875rem;">No data found for this period</div>`;
        return;
    }

    sortedCategories.forEach((cat, index) => {
        const color = colors[index % colors.length];
        const percentage = (cat.amount / total) * 100;
        const deg = (percentage / 100) * 360;

        conicString += `${color} ${currentDeg}deg ${currentDeg + deg}deg, `; 
        currentDeg += deg;

        legendsList.innerHTML += `
            <div class="legend-item">
                <div style="display: flex; align-items: center;">
                    <div class="legend-color" style="background-color: ${color}"></div>
                    <div class="legend-name">${cat.name} <span style="color:#6b7280; font-size:0.7rem; font-weight:normal;">(${percentage.toFixed(1)}%)</span></div>
                </div>
                <div class="legend-amount">${userCurrency}${cat.amount.toLocaleString()}.00</div>
            </div>
        `;
    });
    document.getElementById('expenseDoughnutChart').style.background = `conic-gradient(${conicString.slice(0, -2)})`;
}

function updateTransactionsTable() {
    const tbody = document.querySelector(".transactions-table tbody"); 
    tbody.innerHTML = "";
    let dataToShow = [...transactions];

    if (window.selectedTableCategories && window.selectedTableCategories.length > 0) {
        dataToShow = dataToShow.filter(t => window.selectedTableCategories.includes(t.category));
    }

    if (currentFilter.type !== 'all' && currentFilter.value) {
        dataToShow = dataToShow.filter(t => {
            if (currentFilter.type === 'date') return t.date === currentFilter.value; 
            else if (currentFilter.type === 'month' || currentFilter.type === 'year') return t.date.startsWith(currentFilter.value); 
            return true;
        });
    }

    if (currentSort.column === 'amount') {
        dataToShow.sort((a, b) => {
            let valA = Math.abs(a.amount); let valB = Math.abs(b.amount);
            if (valA < valB) return currentSort.direction === 'asc' ? -1 : 1;
            if (valA > valB) return currentSort.direction === 'asc' ? 1 : -1;
            return 0;
        });
    } else {
        dataToShow.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
    }

    dataToShow.forEach((transaction) => {
        const row = document.createElement("tr");
        const formattedDate = new Date(transaction.date).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
        let amountDisplay = transaction.amount > 0 ? `+${userCurrency}${transaction.amount.toLocaleString()}.00` : `-${userCurrency}${Math.abs(transaction.amount).toLocaleString()}.00`;

        const recurringVal = transaction.recurring === true ? 'monthly' : (transaction.recurring === false ? 'none' : (transaction.recurring || 'none'));
        const isRecur = recurringVal !== 'none';
        
        let actionButtons = '';

        if (transaction.isAutoGenerated) {
            actionButtons = `
                <button class="action-btn" title="Auto-Generated (Edit Original)" disabled style="opacity: 0.5; cursor: not-allowed;">
                    <i class="fas fa-repeat" style="color: #9ca3af;"></i>
                </button>
                <button class="action-btn" onclick="window.deleteTransaction('${transaction.docId}', ${transaction.id})" title="Delete Transaction">
                    <i class="fas fa-trash-alt" style="color: #ef4444;"></i>
                </button>
            `;
        } else {
            const recurIconColor = isRecur ? '#3b82f6' : '#9ca3af';
            const recurTooltip = isRecur ? `Recurring ${recurringVal.toUpperCase()} (Click to manage)` : 'Make Recurring';
            
            actionButtons = `
                <button class="action-btn" onclick="window.toggleRecurring('${transaction.docId}', ${transaction.id})" title="${recurTooltip}">
                    <i class="fas fa-repeat" style="color: ${recurIconColor};"></i>
                </button>
                <button class="action-btn" onclick="window.deleteTransaction('${transaction.docId}', ${transaction.id})" title="Delete Transaction">
                    <i class="fas fa-trash-alt" style="color: #ef4444;"></i>
                </button>
            `;
        }

        row.innerHTML = `
            <td>${formattedDate}</td>
            <td>${transaction.category}</td>
            <td style="color: ${transaction.amount > 0 ? "#10b981" : "#ef4444"}">${amountDisplay}</td>
            <td><span class="status-success">${transaction.status}</span></td>
            <td style="display: flex; gap: 0.5rem; border-bottom: none;">
                ${actionButtons}
            </td>
        `;
        tbody.appendChild(row);
    });

    if (dataToShow.length === 0) tbody.innerHTML = `<tr><td colspan="5" style="text-align: center; padding: 2rem; color: #6b7280;">No transactions found for this period.</td></tr>`;
    updateSortIcons();
}

window.sortTable = function(column) { 
    if (column === 'amount') {
        if (currentSort.column === column) { currentSort.direction = currentSort.direction === 'asc' ? 'desc' : 'asc'; } 
        else { currentSort.column = column; currentSort.direction = 'asc'; } 
        updateTransactionsTable(); 
    }
}

function updateSortIcons() { 
    const icon = document.getElementById(`sort-icon-amount`); 
    if (icon) { 
        icon.className = 'fas fa-sort'; 
        if (currentSort.column === 'amount') {
            if (currentSort.direction === 'asc') icon.className = 'fas fa-sort-up';
            else icon.className = 'fas fa-sort-down';
        }
    } 
}

window.initSavingsCompare = function() {
    const years = [...new Set(transactions.map(t => t.date.substring(0,4)))].sort((a,b)=>b-a);
    const s1 = document.getElementById('savingsCompare1');
    const s2 = document.getElementById('savingsCompare2');
    if (s1 && s1.options.length === 0) {
        s1.innerHTML = '<option value="">Select Year</option>'; if(s2) s2.innerHTML = '<option value="">Select Year</option>';
        years.forEach(y => { s1.innerHTML += `<option value="${y}">${y}</option>`; if(s2) s2.innerHTML += `<option value="${y}">${y}</option>`; });
    }
}

window.calculateSavingsCompare = function() {
    const y1 = document.getElementById('savingsCompare1').value;
    const y2 = document.getElementById('savingsCompare2').value;
    const resultBox = document.getElementById('savingsCompareResult');
    if (!resultBox) return;
    if (!y1 || !y2) { resultBox.innerHTML = '<span style="font-size: 0.875rem; color: rgba(255,255,255,0.8);">Select two years to compare</span>'; return; }
    if (y1 === y2) { resultBox.innerHTML = '<span style="font-size: 0.875rem; color: #f87171;">Cannot compare the same year.</span>'; return; }

    let y1Saved = 0; let y2Saved = 0;
    transactions.forEach(t => {
        const year = t.date.substring(0,4);
        if (year === y1) y1Saved += t.amount;
        if (year === y2) y2Saved += t.amount;
    });
    const diff = y1Saved - y2Saved;
    const isPositive = diff >= 0;
    resultBox.innerHTML = `
        <div style="font-size: 0.75rem; color: rgba(255,255,255,0.8); margin-bottom: 0.25rem;">${y1} vs ${y2}</div>
        <div style="font-size: 1.25rem; font-weight: bold; color: ${isPositive ? '#34d399' : '#f87171'};">${isPositive ? '<i class="fas fa-arrow-up"></i>' : '<i class="fas fa-arrow-down"></i>'} ${userCurrency}${Math.abs(diff).toLocaleString()}</div>
        <div style="font-size: 0.7rem; color: rgba(255,255,255,0.7); margin-top: 0.25rem;">${isPositive ? `You saved more in ${y1}` : `You saved less in ${y1}`}</div>
    `;
}

window.initOverviewFilters = function() {
    availableYears = [...new Set(transactions.map(t => t.date.substring(0,4)))].sort((a,b)=>b-a); 
    if (availableYears.length === 0) availableYears = [new Date().getFullYear().toString()];
    const y1 = document.getElementById('overviewYear1');
    y1.innerHTML = ''; availableYears.forEach(y => { y1.innerHTML += `<option value="${y}">${y}</option>`; }); 
    window.updateYear2Options(); window.renderOverviewChart();
}

window.updateYear2Options = function() {
    const y1Val = document.getElementById('overviewYear1').value;
    const y2 = document.getElementById('overviewYear2');
    const currentY2Val = y2.value;
    y2.innerHTML = '<option value="none">None</option>';
    availableYears.forEach(y => { if (y !== y1Val) y2.innerHTML += `<option value="${y}">${y}</option>`; });
    if (currentY2Val !== y1Val && currentY2Val !== 'none') y2.value = currentY2Val; else y2.value = 'none';
}

window.handleYear1Change = function() { window.updateYear2Options(); window.renderOverviewChart(); }
window.handleYear2Change = function() {
    const y2Val = document.getElementById('overviewYear2').value;
    if (y2Val !== 'none') window.openFullscreenChart();
    window.renderOverviewChart();
}

window.openFullscreenChart = function() {
    if (document.body.classList.contains('fullscreen-active')) return;
    document.body.classList.add('fullscreen-active');
    document.getElementById('overviewChartCard').classList.add('is-fullscreen');
    document.getElementById('closeOverviewBtn').style.display = 'flex';
}

window.closeFullscreenChart = function() {
    document.body.classList.remove('fullscreen-active');
    document.getElementById('overviewChartCard').classList.remove('is-fullscreen');
    document.getElementById('closeOverviewBtn').style.display = 'none';
    document.getElementById('overviewYear2').value = 'none';
    window.renderOverviewChart();
}

window.renderOverviewChart = function() {
    const timeframe = document.getElementById('overviewTimeframe').value;
    const year1 = document.getElementById('overviewYear1').value || new Date().getFullYear().toString();
    const year2 = document.getElementById('overviewYear2').value || 'none';
    const isCompare = year2 !== 'none' && timeframe !== 'yearly'; 
    const titleEl = document.getElementById('overviewMainTitle');

    if (timeframe === 'yearly') { titleEl.textContent = "Yearly Overview"; document.getElementById('overviewComparisonSelectors').style.display = 'none'; } 
    else if (timeframe === 'quarterly') { titleEl.textContent = "Quarterly Overview"; document.getElementById('overviewComparisonSelectors').style.display = 'flex'; } 
    else { titleEl.textContent = "Monthly Overview"; document.getElementById('overviewComparisonSelectors').style.display = 'flex'; }

    let labels = [];
    if (timeframe === 'monthly') labels = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
    else if (timeframe === 'quarterly') labels = ['Q1','Q2','Q3','Q4'];
    else if (timeframe === 'yearly') { 
        labels = [...new Set(transactions.map(t => t.date.substring(0,4)))].sort((a,b)=>a-b); 
        if (labels.length === 0) labels = [new Date().getFullYear().toString()]; 
    }

    let data = {}; labels.forEach(l => { data[l] = { y1Inc: 0, y1Exp: 0, y2Inc: 0, y2Exp: 0 }; });

    transactions.forEach(t => {
        const y = t.date.substring(0,4); const m = parseInt(t.date.substring(5,7)) - 1; 
        const amt = Math.abs(t.amount); const isInc = t.amount > 0;
        if (timeframe === 'yearly') { 
            if (data[y]) { if (isInc) data[y].y1Inc += amt; else data[y].y1Exp += amt; } 
        } else if (timeframe === 'quarterly') {
            const qLabel = labels[Math.floor(m / 3)];
            if (y === year1) { if (isInc) data[qLabel].y1Inc += amt; else data[qLabel].y1Exp += amt; } 
            else if (isCompare && y === year2) { if (isInc) data[qLabel].y2Inc += amt; else data[qLabel].y2Exp += amt; }
        } else if (timeframe === 'monthly') {
            const mLabel = labels[m];
            if (y === year1) { if (isInc) data[mLabel].y1Inc += amt; else data[mLabel].y1Exp += amt; } 
            else if (isCompare && y === year2) { if (isInc) data[mLabel].y2Inc += amt; else data[mLabel].y2Exp += amt; }
        }
    });

    let maxVal = 1; labels.forEach(l => { maxVal = Math.max(maxVal, data[l].y1Inc, data[l].y1Exp, data[l].y2Inc, data[l].y2Exp); });
    const chartContainer = document.getElementById('overviewChartContainer'); chartContainer.innerHTML = '';

    labels.forEach(l => {
        const d = data[l]; const hasData = d.y1Inc > 0 || d.y1Exp > 0 || d.y2Inc > 0 || d.y2Exp > 0;
        const h1Inc = (d.y1Inc / maxVal) * 100 * 0.85; const h1Exp = (d.y1Exp / maxVal) * 100 * 0.85;
        let h2Inc = 0; let h2Exp = 0;
        if (isCompare) { h2Inc = (d.y2Inc / maxVal) * 100 * 0.85; h2Exp = (d.y2Exp / maxVal) * 100 * 0.85; }
        
        let groupHTML = `<div class="chart-bar-group">`;
        if (hasData) {
            const maxH = Math.max(h1Inc, h1Exp, h2Inc, h2Exp);
            let tooltipHTML = `<div class="chart-tooltip" style="bottom: ${maxH}%; margin-bottom: 12px;"><div class="tooltip-month">${l} ${timeframe !== 'yearly' ? year1 : ''}</div><div class="tooltip-income">Income: ${userCurrency}${d.y1Inc.toLocaleString()}</div><div class="tooltip-expense">Expenses: ${userCurrency}${d.y1Exp.toLocaleString()}</div>`;
            if (isCompare) tooltipHTML += `<div style="margin-top:6px; border-top:1px solid #e5e7eb; padding-top:6px;"><div class="tooltip-month">${l} ${year2}</div><div class="tooltip-income">Income: ${userCurrency}${d.y2Inc.toLocaleString()}</div><div class="tooltip-expense">Expenses: ${userCurrency}${d.y2Exp.toLocaleString()}</div></div>`;
            groupHTML += tooltipHTML + `</div>`;
        }
        
        groupHTML += `<div class="bars-wrapper" style="display: flex; gap: 4px; align-items: flex-end; justify-content: center; height: 100%;">`;
        groupHTML += `<div class="chart-bar-income" style="height: ${h1Inc}%; width: 14px; background: #10b981; border-radius: 4px 4px 0 0;"></div>`;
        groupHTML += `<div class="chart-bar-expense" style="height: ${h1Exp}%; width: 14px; background: #ef4444; border-radius: 4px 4px 0 0;"></div>`;
        if (isCompare) {
            groupHTML += `<div class="chart-bar-income" style="height: ${h2Inc}%; width: 14px; background: #34d399; border-radius: 4px 4px 0 0; opacity: 0.6;"></div>`;
            groupHTML += `<div class="chart-bar-expense" style="height: ${h2Exp}%; width: 14px; background: #f87171; border-radius: 4px 4px 0 0; opacity: 0.6;"></div>`;
        }
        groupHTML += `</div><div class="bar-group-label">${l}</div></div>`; 
        chartContainer.innerHTML += groupHTML;
    });
}

window.toggleCard = function(cardId, chevronId) {
    const grid = document.getElementById('mainGrid');
    const isExpanding = !grid.classList.contains('has-expanded-card');
    document.getElementById('incomeCard').classList.remove('is-expanded');
    document.getElementById('expenseCard').classList.remove('is-expanded');
    document.getElementById('budgetCard').classList.remove('is-expanded');
    document.getElementById('incomeChevron').className = "fas fa-chevron-down";
    document.getElementById('expenseChevron').className = "fas fa-chevron-down";
    document.getElementById('budgetChevron').className = "fas fa-chevron-down";
    grid.classList.remove('has-expanded-card');

    if (isExpanding) {
        document.getElementById('incomeCard').classList.add('is-expanded');
        document.getElementById('expenseCard').classList.add('is-expanded');
        document.getElementById('budgetCard').classList.add('is-expanded');
        document.getElementById('incomeChevron').className = "fas fa-chevron-up";
        document.getElementById('expenseChevron').className = "fas fa-chevron-up";
        document.getElementById('budgetChevron').className = "fas fa-chevron-up";
        grid.classList.add('has-expanded-card'); 
    }
}

window.switchDonutType = function(type) { 
    donutChartType = type; 
    document.getElementById('tabExpense').classList.toggle('active', type === 'expense'); 
    document.getElementById('tabIncome').classList.toggle('active', type === 'income'); 
    if (type === 'expense') document.getElementById('donutChartTitle').textContent = 'Expense Overview';
    else document.getElementById('donutChartTitle').textContent = 'Income Overview';
    updateExpenseChart(); 
}

window.toggleExpenseChartFilter = function(e) { e.stopPropagation(); document.getElementById('expenseChartFilterDropdown').classList.toggle('show'); }

window.updateExpenseChartFilterInput = function() { 
    const type = document.getElementById('expenseChartFilterType').value; 
    const container = document.getElementById('expenseChartFilterInputContainer'); 
    if (type === 'month') container.innerHTML = '<input type="month" class="form-input" id="expenseChartFilterValue" style="padding: 0.5rem; font-size: 0.875rem;">'; 
    else if (type === 'year') { 
        let yearOptions = '<option value="">Select Year</option>'; 
        for (let i = new Date().getFullYear() - 5; i <= new Date().getFullYear() + 5; i++) yearOptions += `<option value="${i}">${i}</option>`; 
        container.innerHTML = `<select class="form-select" id="expenseChartFilterValue" style="padding: 0.5rem; font-size: 0.875rem;">${yearOptions}</select>`; 
    } else if (type === 'all') container.innerHTML = ''; 
}

window.applyExpenseChartFilter = function() { 
    const type = document.getElementById('expenseChartFilterType').value; 
    let value = ''; 
    if (type !== 'all') { 
        const valEl = document.getElementById('expenseChartFilterValue'); 
        if (!valEl || !valEl.value) { alert('Please select a value to filter by.'); return; } 
        value = valEl.value; 
    } 
    expenseChartCurrentFilter = { type, value }; 
    document.getElementById('expenseChartFilterDropdown').classList.remove('show'); 
    const btn = document.getElementById('expenseChartFilterBtn'); 
    if (type === 'all') { btn.classList.remove('active-filter'); btn.innerHTML = '<i class="fas fa-filter"></i> Filter'; } 
    else { btn.classList.add('active-filter'); btn.innerHTML = '<i class="fas fa-filter"></i> Filtered'; } 
    updateExpenseChart(); 
}

window.clearExpenseChartFilter = function() { 
    expenseChartCurrentFilter = { type: 'month', value: currentMonthStr }; 
    document.getElementById('expenseChartFilterType').value = 'month'; 
    window.updateExpenseChartFilterInput(); 
    const valInput = document.getElementById('expenseChartFilterValue'); 
    if (valInput) valInput.value = currentMonthStr; 
    document.getElementById('expenseChartFilterDropdown').classList.remove('show'); 
    const btn = document.getElementById('expenseChartFilterBtn'); 
    btn.classList.remove('active-filter'); btn.innerHTML = '<i class="fas fa-filter"></i> Filter'; 
    updateExpenseChart(); 
}

window.resetExpenseChart = function() { window.clearExpenseChartFilter(); showNotification("Chart filter reset", "info"); }

window.toggleFilterMenu = function(e) { e.stopPropagation(); document.getElementById('filterDropdown').classList.toggle('show'); }

window.updateFilterInput = function() { 
    const type = document.getElementById('filterType').value; 
    const container = document.getElementById('filterInputContainer'); 
    if (type === 'date') container.innerHTML = '<input type="date" class="form-input" id="filterValue" style="padding: 0.5rem; font-size: 0.875rem;">'; 
    else if (type === 'month') container.innerHTML = '<input type="month" class="form-input" id="filterValue" style="padding: 0.5rem; font-size: 0.875rem;">'; 
    else if (type === 'year') { 
        let yearOptions = '<option value="">Select Year</option>'; 
        for (let i = new Date().getFullYear() - 5; i <= new Date().getFullYear() + 5; i++) yearOptions += `<option value="${i}">${i}</option>`; 
        container.innerHTML = `<select class="form-select" id="filterValue" style="padding: 0.5rem; font-size: 0.875rem;">${yearOptions}</select>`; 
    } 
}

window.applyFilter = function() { 
    const type = document.getElementById('filterType').value; 
    const value = document.getElementById('filterValue').value; 
    if (!value) { alert('Please select a date/value to filter by.'); return; } 
    currentFilter = { type, value }; 
    document.getElementById('filterDropdown').classList.remove('show'); 
    const btn = document.getElementById('mainFilterBtn'); 
    btn.classList.add('active-filter'); btn.innerHTML = '<i class="fas fa-filter"></i> Date Filtered'; 
    updateTransactionsTable(); 
}

window.clearFilter = function() { 
    currentFilter = { type: 'all', value: '' }; 
    if(document.getElementById('filterValue')) document.getElementById('filterValue').value = ''; 
    document.getElementById('filterDropdown').classList.remove('show'); 
    const btn = document.getElementById('mainFilterBtn'); 
    btn.classList.remove('active-filter'); btn.innerHTML = '<i class="fas fa-filter"></i> Date Filter'; 
    updateTransactionsTable(); 
}

window.resetTable = function() { 
    window.clearFilter(); 
    window.clearTableCategoryFilter(new Event('click'));
    currentSort = { column: null, direction: 'asc' }; 
    updateTransactionsTable(); 
    showNotification("Filters and sorting reset", "info"); 
}

// ==========================================================================
// UTILITIES & EVENT LISTENERS
// ==========================================================================
function showNotification(message, type = "success") {
    let container = document.getElementById("notification-container");
    if (!container) {
        container = document.createElement("div");
        container.id = "notification-container";
        container.style.cssText = `position: fixed; top: 2rem; right: 2rem; z-index: 9999; display: flex; flex-direction: column; gap: 10px; pointer-events: none;`;
        document.body.appendChild(container);
    }
    let bgColor = "#10b981"; 
    if (type === "error" || type === "#ef4444") bgColor = "#ef4444"; 
    else if (type === "info" || type === "#3b82f6") bgColor = "#3b82f6"; 
    else if (type.startsWith("#")) bgColor = type; 
    
    const notification = document.createElement("div"); 
    notification.style.cssText = `background: ${bgColor}; color: white; padding: 1rem 1.5rem; border-radius: 8px; box-shadow: 0 4px 12px rgba(0,0,0,0.15); font-weight: 600; pointer-events: auto;`;
    notification.textContent = message; 
    container.appendChild(notification);
    
    setTimeout(() => { if (container.contains(notification)) container.removeChild(notification); }, 3000);
}

window.toggleDarkMode = function() { 
    document.body.classList.toggle('dark-theme'); 
    const isDark = document.body.classList.contains('dark-theme'); 
    updateThemeUI(isDark); 
    localStorage.setItem('theme', isDark ? 'dark' : 'light'); 
}

function updateThemeUI(isDark) { 
    const tIcon = document.getElementById('themeIcon');
    const tText = document.getElementById('themeText'); 
    if (!tIcon || !tText) return; 
    if (isDark) { tIcon.className = 'fas fa-sun'; tText.textContent = 'Light Mode'; } 
    else { tIcon.className = 'fas fa-moon'; tText.textContent = 'Dark Mode'; } 
}

document.addEventListener("DOMContentLoaded", function () {
    const isDark = localStorage.getItem('theme') === 'dark'; 
    if (isDark) document.body.classList.add('dark-theme');
    document.getElementById('expenseChartFilterType').value = 'month'; 
    window.updateExpenseChartFilterInput(); 
    const valInput = document.getElementById('expenseChartFilterValue'); 
    if (valInput) valInput.value = currentMonthStr;
    updateThemeUI(isDark); 

    const profileAvatar = document.getElementById('profileAvatar');
    if (profileAvatar) {
        profileAvatar.addEventListener('click', (e) => { 
            e.stopPropagation(); document.getElementById('profileDropdown')?.classList.toggle('show'); 
        });
    }

    const themeToggleBtn = document.getElementById('themeToggleBtn');
    if (themeToggleBtn) {
        themeToggleBtn.addEventListener('click', (e) => { 
            e.preventDefault(); window.toggleDarkMode(); 
        });
    }
    
    document.addEventListener("keydown", function (e) {
        if (e.key === "Escape") { 
            window.closeModal("incomeModal"); 
            window.closeModal("expenseModal"); 
            window.closeModal("budgetModal"); 
            window.closeModal("profileModal"); 
            window.closeModal("categoryModal");
            window.closeModal("recurringModal");
            window.closeModal("stopRecurringModal"); 
            if (document.body.classList.contains('fullscreen-active')) window.closeFullscreenChart();
        }
        if (e.ctrlKey && e.key === "i") { e.preventDefault(); window.openIncomeModal(); }
        if (e.ctrlKey && e.key === "e") { e.preventDefault(); window.openExpenseModal(); }
    });
});

document.addEventListener('click', (e) => {
    const iModal = document.getElementById("incomeModal");
    const eModal = document.getElementById("expenseModal");
    const bModal = document.getElementById("budgetModal");
    const pModal = document.getElementById("profileModal");
    const cModal = document.getElementById("categoryModal");
    const rModal = document.getElementById("recurringModal");
    const sModal = document.getElementById("stopRecurringModal"); 
    
    if (e.target === iModal) window.closeModal("incomeModal"); 
    if (e.target === eModal) window.closeModal("expenseModal"); 
    if (e.target === bModal) window.closeModal("budgetModal"); 
    if (e.target === pModal) window.closeModal("profileModal");
    if (e.target === cModal) window.closeModal("categoryModal");
    if (e.target === rModal) window.closeModal("recurringModal");
    if (e.target === sModal) window.closeModal("stopRecurringModal");

    const chartCard = document.getElementById('overviewChartCard');
    if (document.body.classList.contains('fullscreen-active') && chartCard && !chartCard.contains(e.target)) {
        window.closeFullscreenChart();
    }

    const pAvatar = document.getElementById('profileAvatar');
    const pDropdown = document.getElementById('profileDropdown');
    if (pDropdown && pAvatar && !pDropdown.contains(e.target) && e.target !== pAvatar) pDropdown.classList.remove('show');
    
    const fDropdown = document.getElementById('filterDropdown');
    const fBtn = document.getElementById('mainFilterBtn');
    if (fDropdown && fBtn && !fDropdown.contains(e.target) && !fBtn.contains(e.target)) fDropdown.classList.remove('show');
    
    const expChartDropdown = document.getElementById('expenseChartFilterDropdown');
    const expChartBtn = document.getElementById('expenseChartFilterBtn');
    if (expChartDropdown && expChartBtn && !expChartDropdown.contains(e.target) && !expChartBtn.contains(e.target)) expChartDropdown.classList.remove('show');

    const tableCatDropdown = document.getElementById('tableCategoryFilterDropdown');
    if (tableCatDropdown && !tableCatDropdown.contains(e.target) && !e.target.closest('th')) {
        tableCatDropdown.classList.remove('show');
    }
});
